* What does it do?

Uses Rofi (https://github.com/davatorium/rofi) to search for files using the file’s full path and opens them with xdg-open. For the sake of speed, the search is limited to the directories listed in the find command in rofi-file-search.sh. 

The script automatically saves previous search terms and re-opens rofi with the same search text. To delete the previous search terms, type C-a C-k. 

Also logs files opened and enables access to recent files via rofi-recent-files.sh. 

* Installation

Make sure the following are executable and in your PATH (or symlink them):

- quote-splitter.py

- rofi-file-selector.sh

- rofi-recent-files.sh

Currently, the log files are assumed to be in ~/Code/rofi-file-selector

The log files are:
- xdg-open-log.log
- rofi-file-selector.conf


* FAQ
Q. Why is there a python script?

A. Because I couldn’t figure out how to parse Rofi’s output in Bash quickly, I got frustrated, and I used whatever worked. 

Q. Do you know your code sucks?

A. Yup. 
